CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE table STUDENTS(
	NAME VARCHAR(50),
    AGE INT,
    MARKS INT
);

INSERT INTO STUDENTS 
	(NAME,AGE,MARKS)
    VALUES('TALHA',20,95);
INSERT INTO STUDENTS
	(NAME,AGE,MARKS)
    VALUES('AHMED',20,80);
    
INSERT INTO STUDENTS
	(NAME,AGE,MARKS)
    VALUES('ALI',18,99);
    

DELETE FROM STUDENTS;
SET SQL_SAFE_UPDATES = 0;

SELECT * FROM STUDENTS WHERE MARKS>=80;
SELECT * FROM STUDENTS WHERE MARKS<85;

SELECT*FROM STUDENTS WHERE MARKS>80 AND AGE>19;

SELECT * FROM STUDENTS WHERE MARKS>90 OR AGE<20;
USE SCHOOL;
SELECT * FROM STUDENTS order by MARKS;

SELECT * FROM STUDENTS order by MARKS DESC;
SELECT * FROM STUDENTS ORDER BY MARKS  DESC LIMIT 2;
SELECT * FROM STUDENTS order by MARKS LIMIT 1;

INSERT INTO STUDENTS 
(NAME,AGE,MARKS)
VALUES('ALIYAN',90,19);

INSERT INTO STUDENTS 
(NAME,AGE,MARKS)
VALUES('AZLAN',89,20);
INSERT INTO STUDENTS
(NAME,AGE,MARKS)
VALUES('SHYAN',60,21);
SELECT * FROM STUDENTS;
SELECT * FROM STUDENTS WHERE MARKS>70;
SELECT* FROM STUDENTS ORDER BY AGE;

SELECT * FROM STUDENTS ORDER BY MARKS DESC;

SELECT * FROM STUDENTS WHERE AGE >70 OR MARKS >70;

UPDATE STUDENTS SET MARKS = 59 WHERE NAME= 'SHYAN';
SET SQL_SAFE_UPDATES = 0;
SELECT * FROM STUDENTS;
UPDATE STUDENTS SET MARKS = 90 WHERE NAME='AZLAN';
SELECT * FROM STUDENTS;
DELETE FROM STUDENTS WHERE NAME='AZLAN';
SELECT *FROM STUDENTS WHERE NAME='AZLAN';
select *FROM STUDENTS ;
SELECT DISTINCT AGE FROM STUDENTS;
SELECT COUNT(*) FROM STUDENTS;
select SUM(MARKS) FROM STUDENTS;
select AVG(MARKS) FROM STUDENTS;
SELECT MAX(MARKS) FROM STUDENTS;
SELECT MIN(MARKS) FROM STUDENTS;

SELECT AGE,COUNT(*) FROM STUDENTS group by AGE;
SELECT * FROM STUDENTS;
select age, count(*) from students group by age having count(*)>1;
USE SCHOOL;
SELECT * FROM STUDENTS WHERE NAME LIKE 'A%';
SELECT * FROM STUDENTS WHERE NAME LIKE '%A'; 
SELECT * FROM STUDENTS WHERE NAME LIKE '%A%';
SELECT * FROM students WHERE name IN ('Ahmed', 'Ali', 'Sara');
SELECT* FROM STUDENTS WHERE MARKS BETWEEN 70 AND 90;
INSERT INTO STUDENTS (NAME , AGE ,MARKS) VALUES('ZAIN',24,NULL);
SELECT * FROM STUDENTS WHERE MARKS IS NULL;
SELECT * FROM STUDENTS WHERE MARKS IS NOT NULL;


SELECT * FROM STUDENTS WHERE NAME LIKE '%A%';
SELECT * FROM STUDENTS WHERE MARKS between 80 AND 100;
SELECT COUNT(*) FROM STUDENTS;
SELECT AGE , COUNT(*) FROM STUDENTS GROUP BY AGE;
select* FROM STUDENTS WHERE MARKS IS NULL;

SELECT NAME FROM STUDENTS WHERE MARKS >90
UNION
SELECT NAME FROM STUDENTS WHERE AGE<20;