CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE table STUDENTS(
	NAME VARCHAR(50),
    AGE INT,
    MARKS INT
);

INSERT INTO STUDENTS 
	(NAME,AGE,MARKS)
    VALUES('TALHA',20,95);
INSERT INTO STUDENTS
	(NAME,AGE,MARKS)
    VALUES('AHMED',20,80);
    
INSERT INTO STUDENTS
	(NAME,AGE,MARKS)
    VALUES('ALI',18,99);