CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE table STUDENTS(
	NAME VARCHAR(50),
    AGE INT,
    MARKS INT
);

INSERT INTO STUDENTS 
	(NAME,AGE,MARKS)
    VALUES('TALHA',20,95);
INSERT INTO STUDENTS
	(NAME,AGE,MARKS)
    VALUES('AHMED',20,80);
    
INSERT INTO STUDENTS
	(NAME,AGE,MARKS)
    VALUES('ALI',18,99);
    

DELETE FROM STUDENTS;
SET SQL_SAFE_UPDATES = 0;

SELECT * FROM STUDENTS WHERE MARKS>=80;
SELECT * FROM STUDENTS WHERE MARKS<85;

SELECT*FROM STUDENTS WHERE MARKS>80 AND AGE>19;

SELECT * FROM STUDENTS WHERE MARKS>90 OR AGE<20;
USE SCHOOL;
SELECT * FROM STUDENTS order by MARKS;

SELECT * FROM STUDENTS order by MARKS DESC;
SELECT * FROM STUDENTS ORDER BY MARKS  DESC LIMIT 2;
SELECT * FROM STUDENTS order by MARKS LIMIT 1;

INSERT INTO STUDENTS 
(NAME,AGE,MARKS)
VALUES('ALIYAN',90,19);

INSERT INTO STUDENTS 
(NAME,AGE,MARKS)
VALUES('AZLAN',89,20);
INSERT INTO STUDENTS
(NAME,AGE,MARKS)
VALUES('SHYAN',60,21);
SELECT * FROM STUDENTS;
SELECT * FROM STUDENTS WHERE MARKS>70;
SELECT* FROM STUDENTS ORDER BY AGE;

SELECT * FROM STUDENTS ORDER BY MARKS DESC;

SELECT * FROM STUDENTS WHERE AGE >70 OR MARKS >70;

UPDATE STUDENTS SET MARKS = 59 WHERE NAME= 'SHYAN';
SET SQL_SAFE_UPDATES = 0;
SELECT * FROM STUDENTS;
UPDATE STUDENTS SET MARKS = 90 WHERE NAME='AZLAN';
SELECT * FROM STUDENTS;

